name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      IMAGE: "istari"
      IMAGE_FRONTEND: "istari-f"

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

#      - name: Docker Compose Action
#        uses: isbang/compose-action@v1.0.0
#        with:
#          compose-file: './docker-compose.yml redis-01'

      - name: Build
        run: make build

      - name: Start_Redis
        run: IMAGE=istari IMAGE_FRONTEND=istari-f docker-compose up redis-01

      - name: Test
        run: make test

      - name: Lint
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
          make lint

      - name: Security
        run: |
          go get github.com/securego/gosec/cmd/gosec
          make sec

